// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotTrack.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SpotTrack.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612214600_AddProfilesBoundedContext")]
    partial class AddProfilesBoundedContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_admins");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Admin", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("dni");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_admins_email");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id")
                                .HasName("p_k_admins");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_admins_admins_id");
                        });

                    b.Navigation("Dni")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotTrack.Platform.Profiles.Domain.Model.Aggregates.Client", b =>
                {
                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("dni");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_clients_email");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.OwnsOne("SpotTrack.Platform.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id")
                                .HasName("p_k_clients");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_clients_clients_id");
                        });

                    b.Navigation("Dni")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
